reuse ca certificates

diff --git a/gen-ca b/gen-ca
--- a/gen-ca
+++ b/gen-ca
@@ -9,6 +9,9 @@ scriptName=$(basename "${THIS}")
 VERBOSE=0
 DURATION=365 # 1 year
 
+# Load common functions
+source "$DIR/common.sh"
+
 # Help Screen
 help() {
   echo -n "${scriptName} [OPTIONS] -c=US --state=California
@@ -30,6 +33,51 @@ Generate self-signed root CA using OpenSSL
 "
 }
 
+# Prompt for variables that were not provided in arguments
+checkVariables() {
+  # Country
+  if [ -z "$C" ]; then
+    echo -n "Country Name (2 letter code) [AU]: "
+    read -r C
+  fi
+
+  # State
+  if [ -z "$ST" ]; then
+    echo -n "State or Province Name (full name) [Some-State]: "
+    read -r ST
+  fi
+
+  # Locality
+  if [ -z "$L" ]; then
+    echo -n "Locality Name (eg, city) []: "
+    read -r L
+  fi
+
+  # Organization
+  if [ -z "$O" ]; then
+    echo -n "Organization Name (eg, company) [Internet Widgits Pty Ltd]: "
+    read -r O
+  fi
+
+  # Organizational Unit
+  if [ -z "$OU" ]; then
+    echo -n "Organizational Unit Name (eg, section) []: "
+    read -r OU
+  fi
+
+  # Common Name
+  if [ -z "$CN" ]; then
+    echo -n "Common Name (e.g. server FQDN or YOUR name) []: "
+    read -r CN
+  fi
+
+  # Email Address
+  if [ -z "$emailAddress" ]; then
+    echo -n "Email Address []: "
+    read -r emailAddress
+  fi
+}
+
 # Build root CA certificate
 build() {
   # Set OUTPATH if not yet
@@ -43,9 +91,28 @@ build() {
   openssl req -x509 -new -nodes -key "${OUTPATH}ca.key" -sha256 -days "${DURATION}" -out "${OUTPATH}ca.pem" -subj "/C=${C}/ST=${ST}/L=${L}/O=${O}/OU=${OU}/CN=${CN}/emailAddress=${emailAddress}"
 }
 
-source "$DIR/common.sh"
+# Process Arguments
+while [ "$1" != "" ]; do
+  PARAM=$(echo "$1" | awk -F= '{print $1}')
+  VALUE=$(echo "$1" | awk -F= '{print $2}')
+  case $PARAM in
+    -h|--help) help; safeExit ;;
+    -c|--country) C=$VALUE ;;
+    -s|--state) ST=$VALUE ;;
+    -l|--locality) L=$VALUE ;;
+    -o|--organization) O=$VALUE ;;
+    -u|--unit) OU=$VALUE ;;
+    -n|--common-name) CN=$VALUE ;;
+    -e|--email) emailAddress=$VALUE ;;
+    -p|--path) OUTPATH=$VALUE; testPath ;;
+    -d|--duration) DURATION=$VALUE ;;
+    -v|--verbose) VERBOSE=1 ;;
+    *) echo "ERROR: unknown parameter \"$PARAM\""; help; exit 1 ;;
+  esac
+  shift
+done
+
 checkVariables
 sanitize
 build
-# showVals
 safeExit
diff --git a/self-signed-tls b/self-signed-tls
--- a/self-signed-tls
+++ b/self-signed-tls
@@ -9,6 +9,9 @@ scriptName=$(basename "${THIS}")
 VERBOSE=0
 DURATION=365 # 1 year
 
+# Load common functions
+source "$DIR/common.sh"
+
 # Help Screen
 help() {
   echo -n "${scriptName} [OPTIONS] -c=US --state=California
@@ -16,13 +19,9 @@ help() {
 Generate self-signed TLS certificate using OpenSSL
 
  Options:
-  -c|--country         Country Name (2 letter code)
-  -s|--state           State or Province Name (full name)
-  -l|--locality        Locality Name (eg, city)
-  -o|--organization    Organization Name (eg, company)
-  -u|--unit            Organizational Unit Name (eg, section)
   -n|--common-name     Common Name (e.g. server FQDN or YOUR name)
-  -e|--email           Email Address
+  -c|--ca-cert         CA certificate path
+  -k|--ca-key          CA certificate key
   -p|--path            Path to output generated keys
   -d|--duration        Validity duration of the certificate (in days)
   -h|--help            Display this help and exit
@@ -39,13 +38,7 @@ default_md = sha256
 distinguished_name = dn
 
 [dn]
-C=${C}
-ST=${ST}
-L=${L}
-O=${O}
-OU=${OU}
 CN=${CN}
-emailAddress=${emailAddress}
 EOF
 }
 
@@ -61,20 +54,34 @@ DNS.1 = ${CN}
 EOF
 }
 
-# Build TLS Certificate
-build() {
-  # Santizie domain name for file name
-  FILENAME=${CN/\*\./}
-
-  # Set OUTPATH if not yet
-  if [ -v $OUTPATH ]; then
-    OUTPATH="./out/${FILENAME}/"
-    mkdir -p ${OUTPATH}
+# Prompt for variables that were not provided in arguments
+checkVariables() {
+  # Common Name
+  if [ -z "$CN" ]; then
+    echo -n "Common Name (e.g. server FQDN or YOUR name) []: "
+    read -r CN
   fi
 
-  # Generate CA key & crt
-  openssl genrsa -out "${OUTPATH}${FILENAME}_CA.key" 2048
-  openssl req -x509 -new -nodes -key "${OUTPATH}${FILENAME}_CA.key" -sha256 -days "${DURATION}" -out "${OUTPATH}${FILENAME}_CA.pem" -subj "/C=${C}/ST=${ST}/L=${L}/O=${O}/OU=${OU}/CN=${CN}/emailAddress=${emailAddress}"
+  # Select CA key & crt
+  if [ -z "$CA_cert" ] || [ -z "$CA_key" ]; then
+    printf "Please select root CA certificate folder:\n"
+    select d in $DIR/out/root/*/; do
+      test -n "$d" && break
+      echo "> Invalid Number"
+    done
+
+    CA_key="$d/ca.key"
+    CA_cert="$d/ca.pem"
+  fi
+}
+
+# Build TLS Certificate
+build() {
+  # Set OUTPATH if not yet
+  if [ -v $OUTPATH ]; then
+    OUTPATH="./out/certificates/${FILENAME}/"
+    mkdir -p ${OUTPATH}
+  fi
 
   # CSR Configuration
   buildCsrCnf
@@ -86,11 +93,27 @@ build() {
   openssl req -new -sha256 -nodes -out "${OUTPATH}${FILENAME}.csr" -newkey rsa:2048 -keyout "${OUTPATH}${FILENAME}.key" -config <( cat "${OUTPATH}${FILENAME}.csr.cnf" )
 
   # Server certificate
-  openssl x509 -req -in "${OUTPATH}${FILENAME}.csr" -CA "${OUTPATH}${FILENAME}_CA.pem" -CAkey "${OUTPATH}${FILENAME}_CA.key" -CAcreateserial -out "${OUTPATH}${FILENAME}.crt" -days "${DURATION}" -sha256 -extfile "${OUTPATH}/v3.ext"
+  openssl x509 -req -in "${OUTPATH}${FILENAME}.csr" -CA "${CA_cert}" -CAkey "${CA_key}" -CAcreateserial -out "${OUTPATH}${FILENAME}.crt" -days "${DURATION}" -sha256 -extfile "${OUTPATH}/v3.ext"
 }
 
-source "$DIR/common.sh"
+# Process Arguments
+while [ "$1" != "" ]; do
+  PARAM=$(echo "$1" | awk -F= '{print $1}')
+  VALUE=$(echo "$1" | awk -F= '{print $2}')
+  case $PARAM in
+    -h|--help) help; safeExit ;;
+    -n|--common-name) CN=$VALUE ;;
+    -c|--ca-cert) CA_cert=$VALUE ;;
+    -k|--ca-key) CA_key=$VALUE ;;
+    -p|--path) OUTPATH=$VALUE; testPath ;;
+    -d|--duration) DURATION=$VALUE ;;
+    -v|--verbose) VERBOSE=1 ;;
+    *) echo "ERROR: unknown parameter \"$PARAM\""; help; exit 1 ;;
+  esac
+  shift
+done
+
 checkVariables
+sanitize
 build
-showVals
 safeExit
